### PR TITLE
Add opal rspec blog post

### PR DESCRIPTION
**Pull request by wied03**

### CODE REVIEW

**Comment by wied03** [comment]
@elia - get a chance to look at this yet?

**Comment by elia** [comment]
yeah, keep reminding myself to make sure released opal-rails works well with the latest opal-rspec and then publish it (to avoid someone go and try it just to find opal-rails is broken)

**Comment by iliabylich** [comment]
@wied03 https://github.com/opal/opal/issues/1237 seems to be closed. Is it still an issue for `opal-rspec`?

Nice article btw :+1:

**Comment by wied03** [comment]
No it's not an issue. This PR is 6 months old so a lot has changed since then :)

**Comment by elia** [comment]
@wied03 merged, finally! sorry for letting that one go for so long…

**Pull request merged**
